WebApplication/Controllers/AdminController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DAL.Models;
using WebApplication.ViewModels.Admin;

namespace WebApplication.Controllers
{
    [Authorize(Roles = "admin, manager")]
    public class AdminController : Controller
    {
        private readonly ApplicationContext _db;

        public AdminController(ApplicationContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult BooksList()
        {
            var books = _db.Books;
            var model = new BooksListAdminViewModel
            {
                Books = books,
            };
            return View(model);
        }

        [HttpGet]
        public IActionResult BookCreate()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BookCreate(BookCreateAdminViewModel model)
        {
            if (ModelState.IsValid)
            {
                var book = new Book
                {
                    Title = model.Title,
                    Description = model.Description,
                    PublicationYear = model.PublicationYear,
                };
                _db.Books.Add(book);
                _db.SaveChanges();
                return RedirectToAction("BooksList");
            }

            return View();
        }

        public IActionResult BookEdit(string id)
        {
            var book = _db.Books.Find(id);
            var model = new BookCreateAdminViewModel()
            {
                Id = book.Id,
                Title = book.Title,
                Description = book.Description,
                PublicationYear = book.PublicationYear,
                Rating = book.Rating
            };
            return View(model);
        }
        
        [HttpPost]
        public IActionResult BookEdit(BookCreateAdminViewModel model)
        {
            if (ModelState.IsValid)
            {
                var book = _db.Books.Find(model.Id);
                Console.WriteLine(book.PublicationYear);
                book.Title = model.Title;
                book.Description = model.Description;
                book.PublicationYear = model.PublicationYear;
                Console.WriteLine(book.PublicationYear);
                _db.SaveChanges();
                return RedirectToAction("BooksList");
            }
            return View(model);
        }

        [HttpPost]
        public IActionResult BookDelete(BookCreateAdminViewModel model)
        {
            var book = _db.Books.Find(model.Id);
            if (book is null)
                return NotFound();
            _db.Books.Remove(book);
            _db.SaveChanges();
            return RedirectToAction("BooksList");
        }
    }
}

WebApplication/Views/Admin/BookCreate.cshtml
@model WebApplication.ViewModels.Admin.BookCreateAdminViewModel

@{
    ViewBag.Title = "Создание книги";
}
@section Navbar
{}
<form action="" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" value="" placeholder="Название"/>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <input asp-for="Description" class="form-control" value="" placeholder="Описание"/>
    </div>
    <div class="form-group">
        <label asp-for="PublicationYear" class="control-label"></label>
        <input asp-for="PublicationYear" class="form-control" value="" placeholder="Дата публикации"/>
    </div>
    @* <div class="form-group"> *@
    @*     <label asp-for="" class="control-label"></label> *@
    @*     <input asp-for="" class="form-control" value="@Model." /> *@
    @* </div> *@
    @* <div class="form-group"> *@
    @*     <label asp-for="" class="control-label"></label> *@
    @*     <input asp-for="" class="form-control" value="@Model." /> *@
    @* </div> *@
    @* <div class="form-group"> *@
    @*     <label asp-for="" class="control-label"></label> *@
    @*     <input asp-for="" class="form-control" value="@Model." /> *@
    @* </div> *@
    @* <div class="form-group"> *@
    @*     <label asp-for="" class="control-label"></label> *@
    @*     <input asp-for="" class="form-control" value="@Model." /> *@
    @* </div> *@
    @* <div class="form-group"> *@
    @*             <label asp-for="" class="control-label"></label> *@
    @*             <input asp-for="" class="form-control" value="@Model." /> *@
    @*         </div> *@
    <button type="submit" class="btn" asp-controller="Admin" asp-action="BookCreate" formmethod="post">Создать</button>
</form>
<h2>title</h2>

WebApplication/Views/Admin/BookEdit.cshtml
@model WebApplication.ViewModels.Admin.BookCreateAdminViewModel

@{
    ViewBag.Title = "Создание книги";
}
@section Navbar
{}
<form action="" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Id" class="control-label"></label>
        <input asp-for="Id" class="form-control" value="@Model.Id" readonly/>
    </div>
    <div class="form-group">
        <label asp-for="Title" class="control-label"></label>
        <input asp-for="Title" class="form-control" value="@Model.Title"/>
    </div>
    <div class="form-group">
        <label asp-for="Description" class="control-label"></label>
        <input asp-for="Description" class="form-control" value="@Model.Description"/>
    </div>
    <div class="form-group">
        <label asp-for="PublicationYear" class="control-label"></label>
        <input asp-for="PublicationYear" class="form-control" value="@Model.PublicationYear"/>
    </div>
    <div class="form-group">
        <label asp-for="Rating" class="control-label"></label>
        <input asp-for="Rating" class="form-control" value="@Model.Rating" readonly/>
    </div>
    @* <div class="form-group"> *@
    @*     <label asp-for="" class="control-label"></label> *@
    @*     <input asp-for="" class="form-control" value="@Model." /> *@
    @* </div> *@
    @* <div class="form-group"> *@
    @*     <label asp-for="" class="control-label"></label> *@
    @*     <input asp-for="" class="form-control" value="@Model." /> *@
    @* </div> *@
    @* <div class="form-group"> *@
    @*     <label asp-for="" class="control-label"></label> *@
    @*     <input asp-for="" class="form-control" value="@Model." /> *@
    @* </div> *@
    @* <div class="form-group"> *@
    @*     <label asp-for="" class="control-label"></label> *@
    @*     <input asp-for="" class="form-control" value="@Model." /> *@
    @* </div> *@
    @* <div class="form-group"> *@
    @*             <label asp-for="" class="control-label"></label> *@
    @*             <input asp-for="" class="form-control" value="@Model." /> *@
    @*         </div> *@
    <button type="submit" class="btn" asp-controller="Admin" asp-action="BookEdit" formmethod="post">Изменить</button>
    <button type="submit" class="btn" asp-controller="Admin" asp-action="BookDelete" formmethod="post">Удалить</button>
</form>
<h2>title</h2>

WebApplication/Views/Admin/BooksList.cshtml
@model WebApplication.ViewModels.Admin.BooksListAdminViewModel

@{
    ViewBag.Title = "Список книг";
    Layout = "_Layout";
}

@section Navbar
{}

<h2>Список книг</h2>
<table class="table table_search table_sort" id="info-table">
    <input type="text" class="form-control" placeholder="Поиск" id="search-text" onkeyup="tableSearch()">
    <thead>
    <tr>
        <th scope="col">Id</th>
        <th scope="col">Название</th>
        <th scope="col">Описание</th>
        <th scope="col">Дата публикации</th>
        <th scope="col">Рейтинг</th>
        <th scope="col">Адрес изображения</th>
    </tr>
    </thead>
    <tbody>
    @foreach (var book in Model.Books)
    {
        <tr>
            <td>
                <a asp-action="BookEdit" asp-route-id="@book.Id">@book.Id</a>
            </td>
            <td>@book.Title</td>
            <td>@book.Description</td>
            <td>@book.PublicationYear</td>
            <td>@book.Rating</td>
            <td>@book.BookCover</td>
        </tr>
    }
    </tbody>
</table>

<a asp-action="BookCreate">Добавить</a>

@section Scripts
{
    <script src="~/js/admin.js"></script>
}

WebApplication/Views/Admin/Index.cshtml
@section Navbar
{}
<a asp-action="BooksList">Книги</a>