WebApplication/ViewModels/UsefulMongoDb/FilterViewModel.cs
namespace WebApplication.ViewModels.UsefulMongoDb
{
    public class FilterViewModel
    {
        public string Name { get; set; }
        public int? MinPrice { get; set; }
        public int? MaxPrice { get; set; }
    }
}

WebApplication/ViewModels/UsefulMongoDb/IndexViewModel.cs
using System.Collections.Generic;
using DAL.Models;
using WebApplication.Models;

namespace WebApplication.ViewModels.UsefulMongoDb
{
    public class IndexViewModel
    {
        public FilterViewModel Filter { get; set; }
        public IEnumerable<Product> Products { get; set; }
    }
}

WebApplication/Controllers/UsefulMongoDbController.cs
using System.Threading.Tasks;
using DAL.Models;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;
using Microsoft.AspNetCore.Http;
using WebApplication.ViewModels.UsefulMongoDb;

namespace WebApplication.Controllers
{
    public class UsefulMongoDbController : Controller
    {
        private readonly ProductService db;

        public UsefulMongoDbController(ProductService context)
        {
            db = context;
        }

        public async Task<IActionResult> Index(FilterViewModel filter)
        {
            var phones = await db.GetProducts(filter.MinPrice, filter.MaxPrice, filter.Name);
            var model = new IndexViewModel {Products = phones, Filter = filter};
            return View(model);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(Product p)
        {
            if (ModelState.IsValid)
            {
                await db.Create(p);
                return RedirectToAction("Index");
            }

            return View(p);
        }

        public async Task<IActionResult> Delete(string id)
        {
            await db.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

WebApplication/Views/UsefulMongoDb/Create.cshtml
@model DAL.Models.Product
 
@{
    ViewData["Title"] = "Новая модель";
}
<h2>@ViewData["Title"]</h2>
 
<form asp-action="Create" asp-controller="UsefulMongoDb">
    <div>
        <div class="form-group">
            <label asp-for="Name"></label>
            <input type="text" asp-for="Name" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Company"></label>
            <input type="text" asp-for="Company" class="form-control" />
        </div>
        <div class="form-group">
            <label asp-for="Price"></label>
            <input asp-for="Price" class="form-control" />
        </div>
        <div class="form-group">
            <input type="submit" value="Сохранить" class="btn btn-outline-secondary" />
        </div>
    </div>
</form>
 
<div>
    <a asp-controller="Home" asp-action="Index">Вернуться к списку</a>
</div>

WebApplication/Views/UsefulMongoDb/Index.cshtml
@model WebApplication.ViewModels.UsefulMongoDb.IndexViewModel
 
@{
    ViewData["Title"] = "Список товаров";
}
 
<h2>@ViewData["Title"]</h2>

<p>
    <a asp-controller="UsefulMongoDb" asp-action="Create">Добавить</a>
</p>
<table class="table">
    <tr>
        <th>Модель</th>
        <th>Производитель</th>
        <th>Цена</th>
        <th></th>
    </tr>
 
    @foreach (var item in Model.Products)
    {
        <tr>
            <td>@item.Name</td>
            <td>@item.Company</td>
            <td>
                @item.Price.ToString("c")
            </td>
            <td>
                <a asp-controller="UsefulMongoDb" asp-action="Delete" asp-route-id="@item.Id">Удалить</a> |
            </td>
        </tr>
    }
</table>