WebApplication/ViewModels/Book/BookViewModel.cs
using DAL.Models;
using WebApplication.Models;

namespace WebApplication.ViewModels.Book
{
    public class BookViewModel
    {
        public  DAL.Models.Book Book { get; set; }
        public string ReadingStatus { get; set; }
        public string UserId { get; set; }
        public SubscriptionType UserSubscriptionType { get; set; }
        public string Username { get; set; }
    }
}

WebApplication/ViewModels/Book/UserBookPartialsViewModel.cs
using System.Collections.Generic;
using WebApplication.Models;
using WebApplication.ViewModels.Book;

namespace WebApplication.ViewModels
{
    public class UserBookPartialsViewModel
    {
        public string Id { get; set; }
        public string ReadingStatus { get; set; }
        public bool IsNone { get; set; }
        public IEnumerable<BookViewModel> Books { get; set; }

        public UserBookPartialsViewModel(string id, string readingStatus, bool isNone,
            IEnumerable<BookViewModel> books)
        {
            Id = id;
            ReadingStatus = readingStatus;
            IsNone = isNone;
            Books = books;
        }
    }
}

WebApplication/ViewModels/Book/UserBooksViewModel.cs
using System.Collections.Generic;
using WebApplication.Models;
using WebApplication.ViewModels.Book;

namespace WebApplication.ViewModels
{
    public class UserBooksViewModel
    {
        public IEnumerable<BookViewModel> Books { get; set; }
        public IEnumerable<string> ReadingStatus { get; set; }
        public string UserId { get; set; }
    }
}

WebApplication/Controllers/BookController.cs
using System.IO;
using Microsoft.AspNetCore.Mvc;
using WebApplication.Models;
using Microsoft.AspNetCore.Identity;
using System.Linq;
using DAL.Enums;
using DAL.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.EntityFrameworkCore;
using WebApplication.ViewModels.Book;

namespace WebApplication.Controllers
{
    public class BookController : Controller
    {
        private readonly ApplicationContext _db;
        private readonly UserManager<User> _userManager;

        public BookController(UserManager<User> userManager, ApplicationContext db)
        {
            _db = db;
            _userManager = userManager;
        }

        public IActionResult Book(string id)
        {
            var userId = _userManager.GetUserId(User);
            var book = _db.Books.Include(b => b.Authors)
                .Include(b => b.Translators)
                .Include(b => b.CopyrightHolders)
                .Include(b => b.SubscriptionType)
                .Include(b => b.Genres)
                .Include(b => b.Themes)
                .Include(b => b.Reviews)
                .Include(b => b.ReaderDiaries
                    .Where(rd => rd.Book.Id == id && rd.User.Id == userId))
                .ThenInclude(rd => rd.ReadingStatus)
                .Include(b=>b.Reviews)
                .ThenInclude(r=>r.Author)
                .FirstOrDefault(b => b.Id == id);
            if (book is null || book.ReaderDiaries.Count() > 1)
                return NotFound();
            var readingStatus = book.ReaderDiaries.FirstOrDefault()?.ReadingStatus.Description;
            User user = null;
            if (User.Identity != null && User.Identity.IsAuthenticated)
                user = _db.User
                    .Where(u => u.Id == userId)
                    .Include(u => u.Subscriptions)
                    .ThenInclude(s => s.SubscriptionStatus)
                    .Include(u => u.Subscriptions
                        .Where(s => s.SubscriptionStatus.Description == SubscriptionStatusEnums.Current))
                    .ThenInclude(s => s.SubscriptionType)
                    .FirstOrDefault();
            var userSubscriptionType = user != null
                ? user.Subscriptions.FirstOrDefault()?.SubscriptionType
                : _db.SubscriptionTypes
                    .FirstOrDefault(st => st.Description == SubscriptionTypeEnums.Free);
            var username = _userManager.GetUserName(User);
            var model = new BookViewModel
            {
                Book = book,
                ReadingStatus = readingStatus,
                UserId = userId,
                UserSubscriptionType = userSubscriptionType,
                Username = username
            };
            return View(model);
        }

        public IActionResult TextBook(string id)
        {
            var stream = new FileStream(@"C:\Users\user\Desktop\trash\англ\Head_First_Java_2nd_Edition.pdf",
                FileMode.Open);
            return File(stream, "application/pdf");
        }
    }
}

WebApplication/Views/Book/Book.cshtml
@model WebApplication.ViewModels.Book.BookViewModel
@if (User.Identity != null && User.Identity.IsAuthenticated)
{
@section Navbar{
    @await Html.PartialAsync("../Partials/AccountNavbar", Model.UserId)
}
}

@{
    var imageName = (Model.Book.BookCover is null || Model.Book.BookCover.Length == 0) ? "default.jpg" : Model.Book.BookCover;
    var imagePath = $@"media/books/{imageName}";
}
<div class="uk-card uk-card-default uk-grid-collapse uk-child-width-1-2@s uk-margin" uk-grid>
    <div class="uk-card-media-left uk-cover-container">
        <img src="~/@imagePath" alt="" uk-cover>
        <canvas width="600" height="400"></canvas>
    </div>
    <div>
        <div class="uk-card-body">
            <h4 class="uk-card-title">
                @Model.Book.Title
            </h4>
            @if (!string.IsNullOrEmpty(@Model.ReadingStatus))
            {
                @Model.ReadingStatus
            }
            @{
                var subscriptionType = @Model.Book.SubscriptionType;
            }
            <p>@subscriptionType.Description</p>
            <p>@Model.Book.Rating</p>
            @foreach (var author in Model.Book.Authors)
            {
                <p>@author.FirstName @author.LastName</p>
            }
            <p>@Model.Book.PublicationYear</p>
            <h5>О книге</h5>
            <p>@Model.Book.Description</p>
            <h5>Жанры</h5>
            @foreach (var genre in Model.Book.Genres)
            {
                <p>@genre.Description</p>
            }
            <h5>Темы</h5>
            @foreach (var theme in Model.Book.Themes)
            {
                <p>@theme.Description</p>
            }
        </div>
    </div>
</div>


<h5>Правообладатель</h5>
@foreach (var copyrightHolder in Model.Book.CopyrightHolders)
{
    <p>@copyrightHolder.Description</p>
}
<h5>Отзывы</h5>
@foreach (var review in Model.Book.Reviews)
{
    @await Html.PartialAsync("~/Views/Partials/Review.cshtml", review)
    ;

    <div id="chatroom"></div>
}
<h5>Переводчик</h5>
@foreach (var translator in Model.Book.Translators)
{
    <p>@translator.FirstName @translator.LastName</p>
}

@if (@Model.UserId is null)
{
    <p>Для чтения книг необходима регистрация</p>
}


else if (@Model.Book.SubscriptionType.CompareTo(@Model.UserSubscriptionType) <= 0)
{
    <a asp-controller="Book" asp-action="TextBook" asp-route-id="@Model.Book.Id">Начать читать</a>
}

else
{
    <p>Эта книга не доступна с вашей подпиской</p>
}
@if (User.Identity != null && User.Identity.IsAuthenticated && @Model.Book.Reviews.All(r => r.Author.Id != @Model.UserId))
{
    <h3>Оставить комментарий</h3>
    <div id="inputForm">
        <input type="text" class="form-control" id="message" placeholder="Комментарий"/>
        <input type="number" class="form-control" id="rating" placeholder="Рейтинг"/>
        <input type="text" id="book" value="@Model.Book.Id" hidden>
        <input type="text" id="username" value="@Model.Username" hidden>
        <input type="button" class="btn btn-default mt-4" id="sendBtn" value="Отправить"/>
    </div>
}

@section Scripts
{
    <script src="~/js/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/js/signalr/sendComment.js"></script>
}

WebApplication/Views/Book/BookPage.cshtml
@page
@model WebApplication.Views.Book.BookPageModel
@{
    ViewData["Title"] = "Страница книги";
}

WebApplication/Views/Book/Index.cshtml
@page

@{
    ViewData["Title"] = "Книги";
    var searchString = Request.Query["searchString"];
    var sort = Request.Query["sort"];
    var genreId = Request.Query["genreId"];
}
<div id="infinite-scroll">
    <p></p>
    <div class="filterBackground bg-light my-0">
        <div class="container">
            <div class="row">
                <div class="col-md-3" id="filterButton">
                    <div class="dropdown text-center my-2">
                        <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Сортировать
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-route-genreId="@genreId" asp-route-sort="alphabet" asp-route-searchstring="@searchString">По алфавиту</a>
                            <a class="dropdown-item" asp-route-genreId="@genreId" asp-route-sort="rating" asp-route-searchstring="@searchString">По рейтингу</a>
                            <a class="dropdown-item" asp-route-genreId="@genreId" asp-route-sort="new" asp-route-searchstring="@searchString">Сначала новые</a>
                            <a class="dropdown-item" asp-route-genreId="@genreId" asp-route-sort="old" asp-route-searchstring="@searchString">Сначала старые</a>
                        </div>
                    </div>
                </div>
                <form class="form-inline mx-2 my-2 my-lg-0" method="get">
                    @if (genreId.Count > 0)
                    {
        <input type="hidden" name="genreId" value="@genreId">}
                    @if (sort.Count > 0)
                    {
        <input type="hidden" name="sort" value="@sort">}
                    <input id="widthForFilter" class="form-control mr-sm-2" type="search" placeholder="Поиск" aria-label="Search" name="searchString" autocomplete="off" value="@searchString">
                    <button class="btn my-2 my-sm-0" type="submit">Найти</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
var startFrom = 0;
var inProgress = false;

function getQueryParameter(key, value){
    if (value.length == 0){
        return "";
    }

    return "&" + key + "=" + value;
}

function getContent() {
    inProgress = true;
    var query = '/books/content?count=' + startFrom +
        getQueryParameter("genreId", "@genreId") +
        getQueryParameter("sort", "@sort") +
        getQueryParameter("searchString", "@Html.Raw(searchString)");
    fetch(query)
          .then((response) => {
            return response.text();
          })
          .then((data) => {
              $("#infinite-scroll").append(data);
              inProgress = false;
          });
    startFrom += 5;
}

getContent();

if ($("#infinite-scroll").length > 0){
    $(window).scroll(function () {
       if($(window).scrollTop() + $(window).height() >= $(document).height() - 200) {
           getContent();
       }
    });
}
</script>